//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sa_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agendamento
    {
        public int id { get; set; }
        public string cpf { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public string telefone { get; set; }
    }
}
